version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestSaveflowsProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestSaveflowsProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testsaveflows.integrations:e1
  packages:
  - name: TestSaveflowsProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.1014
- serviceName: project.testsaveflows.integrations:customcommit
  packages:
  - name: TestSaveflowsProject
    version: "1.0"
